auth_url = "example.com"
whitelist = [
	"localhost/*"
]

[services.users]
host="http://user-service.default.svc.cluster.local"
port=8080

[services.orders]
host="http://order-service.default.svc.cluster.local"
port=8080

[services.test]
host="https://google.com"
port=443
