whitelist = [
	"localhost/*"
]

[services.users]
path="/users"
target_service="http://user-service.default.svc.cluster.local"
target_port=8080

[services.orders]
path="/orders"
target_service="http://order-service.default.svc.cluster.local"
target_port=8080
